### ISSUE TITLE
Rename repository to Librefox.github.io

### ISSUE THREAD

**Issue by theel0ja** [Librefox/librefox-website#2]
And add custom domain

DNS records:

```
# ALIAS is also known as CNAME by some providers like Cloudflare
# https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

ALIAS librefox.org librefox.github.io
CNAME www.librefox.org librefox.github.io
```

Disable Cloudflare proxy, Github Pages has native SSL.

[Troubleshooting](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/)

**Comment by intika** [comment]
Thank you for the tip :+1:

**Comment by intika** [comment]
By the way you have write access (i guess renaming the git too...)

**Comment by intika** [comment]
Done ;)
