### ISSUE TITLE
write access

### ISSUE THREAD

**Issue by androidacy-user** [Librefox/librefox-website#4]
Can I please have write access to this repo, and librefox main? I'd really like to help contribute, and pull request tends to be messy and sometime ignored

**Comment by shreyasminocha** [comment]
AFAIK we're waiting on a response from Mozilla with respect to copyright stuff. @intika wanted to minimise edits to the repo(s) till we get this response (which is why things have been dormant for some time).

**Comment by androidacy-user** [comment]
Ah. I see, makes sense
As an American, I still find the lack of use of 'z' (minimi(z/s)e odd. :-D

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intika** [comment]
I'll keep you updated soon even if i don't get answer by tomorrow i'll have to make some decisions and choices ;)
i will let you know on the other issue ;)

**Comment by shreyasminocha** [comment]
Fingers crossed :)
